fix: Yarn lint script
wiris/html-integrations pull request #1012
Opened 2024-10-01 16:03 UTC by usantos-at-wiris

## Description

> Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change. Include, if necessary, a description of the proposed solution and the reasoning behind it.

This PR adds the broken functionality to `` yarn lint `` and also autofixes all posible errors

## Type of Change

> Please delete options that are not relevant.

- [ ] Feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (non-breaking change that doesn't add any functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (changes to documentation only)
- [ ] Refactoring (non-breaking change that improves the code structure)

## Checklist

- [X] My code follows the style guidelines of this project ( Run `yarn lint` to check)
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (if applicable)
- [X] My changes generate no new warnings or errors
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] New and existing unit tests pass locally with my changes

## How should be tested? (Manual or Automated Tests)

- **Manual tests:** I have tested this changes manually.

2024-10-01 16:12 UTC, jgonzalez-at-wiris requested changes
Hay cambios que no me convencen del todo. Como tenemos algo delicado entre manos, retrasaría la fusión de esto a cuando estemos más tranquilo, por ejemplo tras la fusión de lo que estamos finalizando de ck5.

2024-10-01 16:12 UTC, jgonzalez-at-wiris commented on packages/devkit/src/mathml.js
> +    } if (mathml.indexOf(`class="wrs_${customEditor}"`) !== -1) {
Este cambio no me inspira confianza (el código original tampoco, sinceramente). Revisemos que no estamos rompiendo nada.

2024-10-01 16:12 UTC, jgonzalez-at-wiris commented on packages/devkit/src/telemeter.js
> +import init, { Telemeter as TelemeterWASM } from "@wiris/telemeter-wasm";
Este cambio de import tampoco me inspira confianza. No sabía que el linter podía hacer algo tan "inteligente".

2024-10-01 16:12 UTC, jgonzalez-at-wiris commented on packages/devkit/telemeter-wasm/telemeter_wasm.js
Juraría que este fichero es autogenerado, no me siento cómo cambiando nada del mismo aunque sean solo cosas de formato.

2025-02-21 10:22 UTC, xjiang-at-wiris approved these changes

2025-02-21 10:42 UTC, carla-at-wiris commented on packages/devkit/src/telemeter.js
> +import init, { Telemeter as TelemeterWASM } from "@wiris/telemeter-wasm";
Este cambio de import no supone un problema en las demos que tenemos aquí, pero no tengo tan claro si cuando lo usen los clientes va a generar problemas

2025-02-21 10:43 UTC, carla-at-wiris requested changes
Los cambios en el fichero `[packages/devkit/telemeter-wasm/telemeter_wasm.js](https://github.com/wiris/html-integrations/pull/1012/files#diff-a4e5e4db28b6efe22fe6dde3f7599c6e949d4c51147a089dbf10c150432d5774)` hay que descartarlos.

2025-02-21 13:06 UTC, ncornaglia-at-wiris submitted a review, later dismissed

2025-02-21 13:31 UTC, xjiang-at-wiris commented on README.md
> +| --------------------------------------------------------------------------------------- | -----------------------------------------------------------------------------------------------------------
Estas tres guiones para qué es? Creo que rompió readme https://github.com/wiris/html-integrations/blob/9b26815afbd443351b06c3bd7ef79193c254e96c/README.md

2025-02-21 13:34 UTC, xjiang-at-wiris commented on docs/demos/README.md
> +| FRAMEWORK | Editor and Version  | EDITOR                                           | Deployment URL for `stable`                               |
No resolvió bien los conflictos, ahora ya no existe stable 🤣

2025-02-21 14:41 UTC, carla-at-wiris commented
Te he cambiado la rama base a la de la release

2025-02-21 14:54 UTC, carla-at-wiris requested changes

2025-02-21 14:54 UTC, carla-at-wiris commented on package.json
> +    "eslint-config-prettier": "^9.1.0",
Hay una nueva major version: `10.0.1`

2025-02-21 14:54 UTC, carla-at-wiris commented on package.json
>      "eslint": "^8.57.0",
Este paquete tiene una nueva major version, y la última versión es `9.20.1`

2025-02-24 09:02 UTC, xjiang-at-wiris commented
Viendo que hay tantos problemas con merge por ser una rama antigua, que tal si mantenemos cambios de 
```
.eslintignore
.eslintrc.js
```

Y ejecutamos yarn lint desde master? Para no perdernos cosas por despiste 🤣

2025-02-24 12:16 UTC, usantos-at-wiris commented
> Viendo que hay tantos problemas con merge por ser una rama antigua, que tal si mantenemos cambios de
> 
> ```
> .eslintignore
> .eslintrc.js
> ```
> 
> Y ejecutamos yarn lint desde master? Para no perdernos cosas por despiste 🤣

Me encanta la idea

2025-02-25 11:32 UTC, jgonzalez-at-wiris approved these changes
Nothing to add to what the rest of the team is commenting. Seems ok for me, so you have my approval!

2025-02-25 11:37 UTC, ncornaglia-at-wiris approved these changes

2025-02-26 11:48 UTC, closed without merging