Impleneting an effective code validation strategy
wiris/html-integrations pull request #238
Opened 2021-05-06 06:58 UTC by carlawiris

Adding linting commands for css, js and html files for all project
Adding the previous commands but for specific files
Linting resources folder
Linting scripts folder
Updating and adding configuration files for the linging process
Updating the README root documentation of the lint section

#taskid 16000

2021-05-10 14:24 UTC, xaviripo requested changes

2021-05-10 14:24 UTC, xaviripo commented on demos/README.md
> +>>>>>>> Fix vulnerabilities on all demos
Watch out, there's an unresolved merge conflict here. You should keep the HEAD change, the Note is outdated.

2021-05-11 07:09 UTC, xaviripo approved these changes

2021-05-11 11:49 UTC, dcanetma approved these changes

2021-05-11 11:49 UTC, merged