Update angular demos to the latest angular version: number 12
wiris/html-integrations pull request #409
Opened 2021-09-13 12:18 UTC by carla-at-wiris

## Description

This PR updates the angular version on angular demos to the latest one, the number 12:

* CKEditor demo: Updated the angular versions to the latest and changes some steps on the demo. Those are specific for our demo configuration, but not to make mathtype work with angular
* Froala demo: Updated the angular versions to the latest and some instructions on the readme file that were outdated.
* Tinymce demo: Updated just the angular versions to the latest.

You'll see that there are no changes on the generic demo. This is because angular V12 updates webpack to V5, which includes some breaking changes that need to be treated carefully on a more specific task. More information on the latest webpack version and how to migrate from V4 to V5 [here](https://webpack.js.org/migrate/5/).

## Steps to reproduce

1. Go to the desired demo folder
2. Run `npm i && npm run start`
3. The demo will open with the latest angular version.

---

[#taskid 13700](https://wiris.kanbanize.com/ctrl_board/2/cards/13700/details/)

2021-09-14 07:06 UTC, dcanet-at-wiris requested changes
Everything looks fine.

But I believe these (2) need to be reviewed:

- I guess we should bump 'patch' version on the package.json demos.

- Also it would be necessary to update the CHANGES.md file.

And I have a question:

- Shouldn't the angular+generic demo be updated, too?

Thanks!

2021-09-14 09:02 UTC, dcanet-at-wiris approved these changes

2021-09-16 09:02 UTC, carla-at-wiris commented on demos/angular/ckeditor5/src/app/app.component.ts
> +import packageInfo from '@wiris/mathtype-ckeditor5/package.json';
The new angular version forces to change the way the parameters from the package.json are obtained. I also checked and we have other files in the project that follow the same methodology.

2021-09-16 13:27 UTC, xripoll-at-wiris commented on demos/angular/ckeditor5/src/app/app.component.ts
> +import packageInfo from '@wiris/mathtype-ckeditor5/package.json';
Okay, if it is consistent, it's good

2021-09-16 13:28 UTC, xripoll-at-wiris approved these changes

2021-09-16 13:36 UTC, dcanet-at-wiris commented
Ready to merge!

2021-09-20 13:30 UTC, merged