Added missing 'www' on documentation wiris.net links
wiris/html-integrations pull request #470
Opened 2021-11-19 11:31 UTC by icaparros-at-wiris

## Description

wiris.net services access has changed and is not allowed to use a service without www in the hostname. Added missing 'www' on documentation wiris.net links.

---

[#taskid 34](https://wiris.kanbanize.com/ctrl_board/2/cards/34/details/)

2021-11-20 15:29 UTC, xripoll-at-wiris approved these changes

2021-11-22 12:38 UTC, carla-at-wiris approved these changes

2021-11-24 16:15 UTC, carla-at-wiris requested changes
This task is included on the Q4 bug-sprint, so the Pull request needs to be done to the branch we have assignaed for the sprint: `KB-15953-BUGSPRINT` instead of the `master` one.

2021-11-25 14:25 UTC, xripoll-at-wiris approved these changes

2021-11-26 14:23 UTC, dcanet-at-wiris requested changes
> This task is included on the Q4 bug-sprint, so the Pull request needs to be done to the branch we have assignaed for the sprint: `KB-15953-BUGSPRINT` instead of the `master` one.

I've changed the PR to the right target branch, @carla-at-wiris .

@icaparros-at-wiris before merging this branch I'm missing an update on the CHANGELOG file.

2021-11-29 07:35 UTC, icaparros-at-wiris commented
> This task is included on the Q4 bug-sprint, so the Pull request needs to be done to the branch we have assignaed for the sprint: `KB-15953-BUGSPRINT` instead of the `master` one.

2021-11-29 08:32 UTC, icaparros-at-wiris commented
Thanks for advising @carla-at-wiris and @dcanet-at-wiris ot change the branch. I updated the CHANGELOG file too.

2021-11-29 10:35 UTC, dcanet-at-wiris approved these changes

2021-12-01 15:42 UTC, carla-at-wiris approved these changes

2021-12-02 13:17 UTC, merged