Remove support to TinyMCE4
wiris/html-integrations pull request #638
Opened 2022-08-17 15:14 UTC by carla-at-wiris

## Description

This PR removes, from the new Mono-repository infrastructure, the TinyMCE4 package and demo, as well as all the documentation related to it. This is because of the deprecation of the module.

## Steps to reproduce

Validate that there's no trace left of the TinyMCE4

---

[#taskid 27920](https://wiris.kanbanize.com/ctrl_board/2/cards/27920/details/)

2022-08-18 07:37 UTC, xripoll-at-wiris requested changes

2022-08-18 07:37 UTC, xripoll-at-wiris commented on packages/tinymce5/editor_plugin.src.js
> +        // Cmd Parameter is needed in TinyMCE5 and onAction parameter is needed in TinyMCE5.
This change doesn't really make sense. Maybe leave this line as-is even though we don't support TinyMCE 4 anymore.

2022-08-18 07:37 UTC, xripoll-at-wiris commented on packages/tinymce5/editor_plugin.src.js
> +          // Cmd Parameter is needed in TinyMCE5 and onAction parameter is needed in TinyMCE5.
Ditto

2022-08-19 08:36 UTC, icaparros-at-wiris requested changes

2022-08-19 08:36 UTC, icaparros-at-wiris commented on README.md
> +| [`@wiris/mathtype-froala`](packages/mathtype-froala)                                    | <a href="https://www.npmjs.com/package/@wiris/mathtype-froala"><img src="https://img.shields.io/npm/v/@wiri
I would change the last column text for `MathType Web for Froala editor` or `MathType Web for Froala 3 or highest version`

2022-08-22 11:18 UTC, xripoll-at-wiris approved these changes

2022-08-25 08:50 UTC, merged