Show a friendly message when going offline with MathType
wiris/html-integrations pull request #760
Opened 2023-01-18 08:01 UTC by carla-at-wiris

## Description

MathType is an online tool, but it gives an error with no explanation when going offline. This PR adds a popup window that warns the user that MathType can't work offline.

## Steps to reproduce

1. install dependencies with `yarn`.
2. Build the plugin with `nx build <PACKAGE>`.
3. Start the desired demo with `nx start <FRAMEWORK>-<PACKAGE>`.
4. Turn off the internet connection.
5. Refresh the page and validate that the popup window with an appropriate message appears
> It's important to validate the content of the popup window so it's appropriate to show to the clients.

---

[#taskid 12739](https://wiris.kanbanize.com/ctrl_board/2/cards/12739/details/)

2023-01-18 10:20 UTC, xripoll-at-wiris requested changes
I'm not sure this is a good user experience. The message only works when the connection is lost before loading the page, and an alert seems to be intrusive.

I think, ideally, we should still open the modal, but display an error message inside.

@jguillen-at-wiris maybe we should get Product involved in this.

2023-01-18 10:20 UTC, xripoll-at-wiris commented on packages/devkit/src/serviceprovider.js
> +    } else window.alert("MathType can not work offline");
"can not" should be "cannot"

2023-01-26 10:53 UTC, carla-at-wiris commented
> I'm not sure this is a good user experience. The message only works when the connection is lost before loading the page, and an alert seems to be intrusive.
> 
> I think, ideally, we should still open the modal, but display an error message inside.
> 
> @jguillen-at-wiris maybe we should get Product involved in this.

I agree, unfortunately, the modal can not be opened properly without internet connection. Maybe we can introduce the message in some way before the errors appear, even though the modal will not have all the MathType features. I also think that product should be involved in this @jguillen-at-wiris

2023-02-28 10:27 UTC, xripoll-at-wiris reviewed
Good job! It works very well. The only quirk I found is that on Froala, the toolbar underneath the new modal stays visible and can be clicked:

![html-froala](https://user-images.githubusercontent.com/85480396/221827063-1d10c880-ebfe-40d8-9acd-78c7be7485fd.png)

2023-02-28 10:27 UTC, xripoll-at-wiris commented on packages/devkit/src/integrationmodel.js
> +      // alert('PARARA');
PARARA

2023-03-02 08:52 UTC, xripoll-at-wiris approved these changes

2023-03-02 08:52 UTC, xripoll-at-wiris commented
Remember to rebase! You have conflicting changes with `master` now that I notice.

2023-04-17 10:20 UTC, icaparros-at-wiris requested changes
Great job!

On Froala the alert svg and the modal close/minimize/maximize icons are not been displayed.
Do you know If this is a bug fixed in another card?

![image](https://user-images.githubusercontent.com/91468181/232455267-930628d6-0797-401d-a52a-37ef9eeb95e2.png)
![image](https://user-images.githubusercontent.com/91468181/232456832-d63b639b-921a-4f8d-9678-5c2bed16e5fe.png)

2023-04-18 10:17 UTC, icaparros-at-wiris approved these changes

2023-04-26 07:35 UTC, merged