Add GitHub information to the demo
wiris/html-integrations pull request #838
Opened 2023-07-26 07:16 UTC by carla-at-wiris

## Description

This PR adds the information of the GitHub branch and commit to the demo pages.

## Steps to reproduce

1. Go to all staging demos.
2. Validate that they all have the new information matching this current branch and its latest commit.

---

[#taskid 34114](https://wiris.kanbanize.com/ctrl_board/2/cards/34114/details/)

2023-07-27 07:51 UTC, xripoll-at-wiris requested changes

2023-07-27 07:51 UTC, xripoll-at-wiris commented on packages/res/git-data.mjs
> +fs.writeFile(__dirname + '/git-data.json', jsonData, (err) => {
If you've already imported `path`, might as well use `path.join` here instead of + for obtaining the full path.

2023-07-27 07:53 UTC, xripoll-at-wiris commented
What do we think about adding the branch info to the `<title>` of the page, so we can tell apart which demo is which just by looking at the tab?

I think it would be nice but not if it hides the rest of the info (framework and editor).

2023-07-31 08:25 UTC, carla-at-wiris commented
> What do we think about adding the branch info to the `<title>` of the page, so we can tell apart which demo is which just by looking at the tab?
> 
> I think it would be nice but not if it hides the rest of the info (framework and editor).

The title of the page is already way too long with the information of the framework and editor, it almost never shows up all the title on the tab, so adding the branch on it would not give us any more information in a regular basis. 
To see the branch in the title, we would have to place the cursor on the tab and wait until the full title shows up, which is more or less the same as opening the page.

2023-08-08 07:50 UTC, xripoll-at-wiris approved these changes

2023-09-29 09:23 UTC, merged