feat: allow set custom headers
wiris/html-integrations pull request #867
Opened 2023-12-15 14:10 UTC by icaparros-at-wiris

## Description

This pull request introduces a new feature that allow users to include custom headers that will be sent on all requests to the wiris.net editor and integration services.

To configure default custom headers, simply update the configuration.ini file in the integration services, adhering to the following format:

```
wiriscustomheaders = key1=value1, key2=value2
```

Additionally, a new function, setHeaders, has been incorporated into the core.js file from devkit. This function allows the modification of custom header values directly from the frontend:

```
window.WirisPlugin.currentInstance.core.setHeaders('key1=value1updated, key2=value2updated')
```

## Steps to reproduce

Read [this document](https://docs.google.com/document/d/1Qk3yCsr5w2UZVTu1LQsjCkINF1tG06u3b4fpfqYAivk/edit) and follow the steps to reproduce:
* The ones on development or testing environment. Both if you want.
* The ones to update the custom headers.

The document will let you test the custom headers on plugins, html-integrations and the viewer.

---

[#taskid 37925](https://wiris.kanbanize.com/ctrl_board/2/cards/37925/details/)

2023-12-18 16:06 UTC, jgonzalez-at-wiris requested changes
En esta tarea tengo las mismas dudas que me surgieron cuando hice lo del hand obligatorio: no se si es correcto poner las funciones donde se han puesto (por ejemplo, que se tenga que acceder directamente al core para manipular los custom headers). Por lo demás, y sin haberlo probado como tal, veo que está OK. (si que he probado la función que convierte una cadena de texto clave=valor a JSON).

2023-12-19 10:16 UTC, carla-at-wiris requested changes
Consider the changes proposed by Jose. Apart from that, all seems okay

2024-01-04 08:22 UTC, carla-at-wiris approved these changes

2024-01-04 08:49 UTC, jgonzalez-at-wiris approved these changes

2024-04-03 16:36 UTC, jgonzalez-at-wiris requested changes

2024-04-03 16:36 UTC, jgonzalez-at-wiris commented on packages/devkit/src/contentmanager.js
> +  setCustomHeaders(headers) {
Esta función confía en que lo que le llega es o bien un `string` o bien es un objeto, ¿estamos seguros de que no se nos escapa ningún otro caso? Habría que revisar todas las llamadas a esta función.

2024-04-03 16:36 UTC, jgonzalez-at-wiris commented on packages/devkit/src/core.src.js
> +  setHeaders(headers) {
Aquí pasa lo mismo que con lo comentado para la función `setCustomHeaders`.

2024-04-03 16:36 UTC, jgonzalez-at-wiris commented on packages/devkit/src/util.js
> +  static convertStringToObject(keyValueString) {
Veo que siempre que se va a usar esta función, antes se comprueba si es de tipo string o no. Creo que tiene sentido que esa lógica esté metida aquí para evitar tanto código repetido.

2024-04-04 11:21 UTC, carla-at-wiris commented on packages/devkit/src/core.src.js
> +  setHeaders(headers) {
Fixed

2024-04-04 11:21 UTC, carla-at-wiris commented on packages/devkit/src/contentmanager.js
> +  setCustomHeaders(headers) {
Fixed

2024-04-10 09:23 UTC, jgonzalez-at-wiris approved these changes

2024-04-10 09:39 UTC, carla-at-wiris commented
Closed due to duplicate of https://github.com/wiris/html-integrations/pull/876

2024-04-10 09:39 UTC, closed without merging