Place correct formular position
wiris/html-integrations pull request #920
Opened 2024-03-19 11:57 UTC by xjiang-at-wiris

## Description

Place correct formular position after inserting an equation after a styled text on Ckeditor4. 

## Steps to reproduce

- Open any CKEditor 4 plugins demo in Chrome
- Empty the editing area
- Switch to italics, or bold, or underline
- Write some text
- Click the MT or CT icon
- Write a formula and click Insert
- Check that the formula is inserted at the end

---

[#taskid 43453](https://wiris.kanbanize.com/ctrl_board/2/cards/43453/details/)

2024-03-19 12:04 UTC, jgonzalez-at-wiris requested changes

2024-03-19 12:04 UTC, jgonzalez-at-wiris commented on CHANGES.md
> +  - fix(ck4): Place correct formular position after inserting an equation.
```suggestion
  - fix(ck4): Place formula in the correct position after inserting italics (or bold or underlined) text in a new line.  
```

2024-03-20 08:42 UTC, xjiang-at-wiris commented on CHANGES.md
> +  - fix(ck4): Place correct formular position after inserting an equation.
Sure! That's better

2024-03-20 12:14 UTC, carla-at-wiris approved these changes

2024-04-10 08:49 UTC, merged