fix(froala): Fix editor bug with Wirisformulas related paste behavior
wiris/html-integrations pull request #948
Opened 2024-04-18 15:48 UTC by usantos-at-wiris

Avoided froala cleanup functions on paste to conserve image attributes, improved legacy code.

(Chore): Change naming and more comments

## Description

The Froala Editor has a built-in cleanup process that removes unwanted HTML tags and attributes from the content. However, this cleanup process can cause issues when dealing with Wirisformulas. To prevent these issues, the code attaches a function to the 'paste.beforeCleanup' event of the Froala Editor. This event is triggered before the cleanup process starts. The regex looks for img tags that have a class attribute containing the word 'Wirisformula'. If a match is found, meaning a Wiris formula is detected, tells the Froala Editor to skip the cleanup process, thus preserving the Wiris formulas in their original state.

## Steps to reproduce

To reproduce
- Copy and paste a mathtype formula or something containing a mathtype formula
- Paste the content into the editor

Issues
- Initially, a pop-up loading window containing the text "Uploading" will appear (Click away to close it)
- Then a console error will trigger (Atob)
- If Froala => 4.2 the paste behavior will paste 2 times the original content and induce a buggy state that makes everything copy 2 times 

---
[#taskid 46612](https://wiris.kanbanize.com/ctrl_board/2/cards/46612/details/)

2024-04-18 15:49 UTC, usantos-at-wiris commented on packages/froala/wiris.src.js
>      });
These changes are not needed but improved the code based on a lint warning

2024-04-19 08:19 UTC, jgonzalez-at-wiris approved these changes
I didn't try the code out but it seems good for me.

2024-04-19 09:11 UTC, carla-at-wiris requested changes
The code is great, and the solution works as expected, great job!

I would suggest updating the Froala demo's version, so that the staging environment has the `4.2.0` version where the error happened, thus we can test the solution without manually updating the code.

2024-04-19 09:11 UTC, carla-at-wiris commented on packages/froala/wiris.src.js
> +    // Froala editor uses a clean up process to remove unwanted tags and attributes. We need to avoid this process for Wiris formulas. If we don't do this, buggy behavior will happen.
I would explain here or in a new line which are the buggy behavior (copy/paste)

2024-04-19 09:11 UTC, carla-at-wiris commented on packages/froala/wiris.src.js
>      this.editorObject.events.on('html.set', function () {
Great job!

2024-04-19 09:53 UTC, xjiang-at-wiris approved these changes

2024-04-19 11:05 UTC, carla-at-wiris approved these changes

2024-04-23 15:36 UTC, merged