KB-45700: Update Telemeter Tracking to Utilize Promises
wiris/html-integrations pull request #954
Opened 2024-04-24 13:04 UTC by usantos-at-wiris

## Description
This PR introduces a significant enhancement to our telemeter tracking functionality by transitioning all tracking actions to utilize promises. The motivation behind this change stems from a recent integration issue encountered with OnlyOffice.

## Steps to Reproduce:
1. Pull the `wiris/telemeter` repo.
2. Initiate the telemeter server by executing `cargo run` and ensure it's operational.
3. Navigate to `packages/devkit/src/Integrationmodel` on this branch.
4. Amend the code from `debug: false` to `debug: true`.
5. Execute `yarn && nx build generic && nx start html-generic` to build the generic editor.
6. Verify the connection of the generic editor to the telemeter server.
7. Interact with the generic editor by inserting formulas, closing, and reopening it.
8. Observe the telemetry actions being accurately tracked on the telemeter server.

[Link to Task: #45700](https://wiris.kanbanize.com/ctrl_board/2/cards/45700/details/)

2024-04-25 15:02 UTC, xjiang-at-wiris approved these changes

2024-04-25 16:44 UTC, jgonzalez-at-wiris requested changes
To make sure the applied changes really have effect, we´d have to `await` all the methods we appended the `async` keyword to... In other words, for example, now that we made `insertFormula` an `async` method, we need to check all places where that method is used and await its execution... This could bring us to an infinity spiral of async/await methods, let's check it at least!

2024-04-26 08:33 UTC, carla-at-wiris commented
> To make sure the applied changes really have effect, we´d have to `await` all the methods we appended the `async` keyword to... In other words, for example, now that we made `insertFormula` an `async` method, we need to check all places where that method is used and await its execution... This could bring us to an infinity spiral of async/await methods, let's check it at least!

The code is thought to run in serial mode, so it may not be an issue to add the async/await where needed. However, take into consideration that there are cyclic methods.

2024-04-29 10:32 UTC, jgonzalez-at-wiris reviewed
Left a comment regarding some refactor code that was interesting to be included in this PR.

2024-04-29 10:32 UTC, jgonzalez-at-wiris commented on packages/devkit/src/modal.js
Changes applies here, except for the `await` keyword, were interesting, we could keep them although it isn´t directly linked to the issue we are fixing here. Alternatively, we could create a new PR just for that change, but I wouldn´t mind including it here for the sake of simplicity.

2024-04-30 08:58 UTC, usantos-at-wiris commented
Sorry for the length of this PR. Fixed a bunch of typos and added a more considerate way to track the closing telemetry.

2024-04-30 09:02 UTC, jgonzalez-at-wiris requested changes

2024-04-30 09:02 UTC, jgonzalez-at-wiris commented on packages/generic/wirisplugin-generic.src.js
> +      this.close();
I can't see any `close` method neither in this class nor in `IntegrationModel`, which this class extends. I'm pretty sure this should fail, am I missing something?

2024-04-30 10:29 UTC, jhernandez-at-wiris approved these changes

2024-04-30 10:29 UTC, jhernandez-at-wiris commented on packages/devkit/src/modal.js
> +    // Make focus come back too.
Esto está explicando, hasta donde he entendido, las lineas:

```
      IntegrationModel.setActionsOnCancelButtons();
      await this.close();
```

pero en concreto la de `setActionsOnCancelButtons()`, quizás va mejor el comentario como doc-string de esa función, tiene uno pero se podría ampliar/mejorar/revisar. Ahí me ha hecho mirar si está haciendo eso y al ir a ver la función `setActionsOnCancelButtons()` es donde vi un comentario similar sobre el foco.

O si tiene sentido el comentario ahí quizás me falta contexto.

2024-04-30 10:29 UTC, jhernandez-at-wiris commented on packages/devkit/src/modal.js
> +        // internet explorer need a dynamic object to apply this property.
```suggestion
        // internet explorer needs a dynamic object to apply this property.
```

2024-04-30 10:39 UTC, usantos-at-wiris commented on packages/devkit/src/modal.js
> +    //* The function was changed to async to ensure that telemetry tracking is completed before closing the modal.
Added an attribute to track the trigger message ! Thanks!

2024-04-30 10:49 UTC, usantos-at-wiris commented on packages/devkit/src/integrationmodel.js
> +        debug: true, // True to show more information about Telemeter's execution and use dev-tools.
Done!

2024-04-30 11:59 UTC, jgonzalez-at-wiris requested changes

2024-04-30 11:59 UTC, jgonzalez-at-wiris commented on packages/generic/wirisplugin-generic.src.js
> +  static Telemeter = {
Why are we converting this field to `static`? On top of that, renaming it may cause retro compatibility issues, I think.

2024-04-30 12:30 UTC, jhernandez-at-wiris approved these changes

2024-04-30 13:48 UTC, jhernandez-at-wiris approved these changes

2024-04-30 13:48 UTC, jhernandez-at-wiris commented on packages/devkit/src/modal.js
> +  async close(trigger) {
It looks great!

2024-04-30 14:07 UTC, carla-at-wiris approved these changes

2024-05-02 13:43 UTC, jgonzalez-at-wiris approved these changes

2024-05-16 13:44 UTC, merged