Respect options passed to data controller on set
wiris/html-integrations pull request #958
Opened 2024-04-29 11:09 UTC by xjiang-at-wiris

## Description

Refactor the functions for 'editor.setData' and 'editor.getData' in CKEditor 5 to accept additional arguments when calling the functions.

## Steps to reproduce

- Open a CKEditor5 demo.
- Check that there are no errors when calling 'editor.setData' and 'editor.getData' in CKEditor 5 (for example, when using source mode to edit).

---
[#taskid 43896](https://wiris.kanbanize.com/ctrl_board/2/cards/43896/details/)

2024-04-29 11:14 UTC, jgonzalez-at-wiris requested changes

2024-04-29 11:14 UTC, jgonzalez-at-wiris commented on packages/ckeditor5/src/plugin.js
> +      e.return = Parser.endParse(imageFormula);
Is this correct? This code seems weird to me.

2024-04-29 15:29 UTC, jgonzalez-at-wiris approved these changes

2024-04-30 10:56 UTC, usantos-at-wiris commented
Please, could you add the changes.md to the pr ?

2024-04-30 10:57 UTC, usantos-at-wiris approved these changes

2024-04-30 12:22 UTC, carla-at-wiris approved these changes
It seems to work as expected and the same way as it does on stable

2024-05-09 07:00 UTC, jhernandez-at-wiris approved these changes

2024-05-16 13:50 UTC, merged