Fix/use strict
wiris/html-integrations pull request #964
Opened 2024-05-13 16:38 UTC by pau-sala-at-wiris

## Description

- Add `strict: true` to the `tsconfig.json` file in the viewer package to enforce stricter typing. This will lead to more robust code and help catch potential bugs at compile time.

## Steps to reproduce
### Dev deployment
- Check the dev deploy [here](https://integrations.wiris.kitchen/fix/use-strict/html/viewer/), it should show the demo viewer and work as expected. 

### Locally
- run: `nx build viewer && nx start html-viewer`, the code should compile and work as expected

## Warning
- Setting strict to true has revealed a number of errors. Resolving some of these is innocuous, but addressing others involves assumptions that are not clear about what the code should do in certain cases. 

---

[#taskid X](https://wiris.kanbanize.com/ctrl_board/2/cards/X/details/) (*Waiting for the card to be created*)

2024-05-17 06:01 UTC, pau-sala-at-wiris commented on packages/viewer/src/retro.ts
> +        node.textContent = (node.textContent?.substring(0,start) as string) + node.textContent?.substring(end + endMathmlTag.length);
Si, ese y algún otro de los puntos que has comentado son los que me daban miedo. Yo sólo haría un casting si es evidente que es correcto, en ese caso no lo es. Por otro lado, sin el strict aquí en tiempo de ejecución habría petado con un `cannot read properties of undefined` al hacer el substring, con lo que para respetar lo que había antes habría que lanzar un error si el textContent no existe, cosa que tampoco me parece que sea lo que se espera. 
Imagino que la solución pasa por evaluar bien el código y definir si esa absencia de textContent es un error (y lanzamos un error), o no puede darse nunca (Y hacemos el casting) o es algo controlado y se define un default que tenga sentido en ese contexto.

2024-05-17 06:08 UTC, pau-sala-at-wiris commented on packages/viewer/src/retro.ts
> +        node.textContent = (node.textContent?.substring(0,start) as string) + node.textContent?.substring(end + endMathmlTag.length);
De todos modos, desde mi punto de vista, ese tipo de funciones son super candidatas a tener unos test unitarios que contemplen esos casos para ahorrarnos ese tipo de cuestiones en un futuro.

2024-05-17 06:37 UTC, pau-sala-at-wiris commented on packages/viewer/src/properties.ts
> +};
Si esa interfaz no se exporta y no queda expuesta al usuario no le veo problema. 
Además hay algo raro que no había visto, en la declaración de la clase Properties: 
```   
config: Config = defaultValues; 
```
Aquí ya se asignan los default values, no entiendo porque en los getters no se devuelve eso directamente. 
Lo cambio, si más adelante vemos que hay que exponer eso ya lo cambiaremos.

2024-05-17 10:56 UTC, jgonzalez-at-wiris approved these changes
Genial trabajo, gracias por tomarte el tiempo de mejorar estos detalles!

Doy el aprobado a nivel de código pero me gustaría que esto lo probáramos a nivel de comportamiento, es decir, ejecutar el código y verificar que todo sigue funcionando igual. Por favor @carla-at-wiris @usantos-at-wiris ¿podriais revisar y ayudar a verificar esto que comento? Gracias!

2024-05-17 10:58 UTC, jgonzalez-at-wiris commented on packages/viewer/src/retro.ts
> +        node.textContent = (node.textContent?.substring(0,start) as string) + node.textContent?.substring(end + endMathmlTag.length);
De acuerdo con lo de las pruebas unitarias, pero no se hasta qué punto son viables debido a que dependenden de nodos que no se hasta qué punto es fácil replicar en un entorno de pruebas o no 🤔

2024-05-17 12:08 UTC, carla-at-wiris requested changes
Given the fact that the branch was originally created from main, there are many conflicts with the modified files, and the staging demo breaks when trying to render new formulas. This last point may be solved if the code aligns with the current master.

2024-05-21 06:21 UTC, pau-sala-at-wiris commented
> Given the fact that the branch was originally created from main, there are many conflicts with the modified files, and the staging demo breaks when trying to render new formulas. This last point may be solved if the code aligns with the current master.

Given the scope and size of the PR I've created a new one from master branch to avoid conflict related issues . We should close this and review the [other one](https://github.com/wiris/html-integrations/pull/969).

2024-05-21 06:26 UTC, closed without merging

2024-05-21 06:26 UTC, pau-sala-at-wiris commented
[Moved to](https://github.com/wiris/html-integrations/pull/969)