Add strict to ts-config
wiris/html-integrations pull request #969
Opened 2024-05-21 06:17 UTC by pau-sala-at-wiris

## Description

- Add `strict: true` to the `tsconfig.json` file in the viewer package to enforce stricter typing. This will lead to more robust code and help catch potential bugs at compile time.

## Steps to reproduce
### Dev deployment
- Check the dev deploy [here](https://integrations.wiris.kitchen/fix/use-strict/html/viewer/), it should show the demo viewer and work as expected. 

### Locally
- run: `nx build viewer && nx start html-viewer`, the code should compile and work as expected

## Warning
- Setting strict to true has revealed a number of errors. Resolving some of these is innocuous, but addressing others involves assumptions that are not clear about what the code should do in certain cases. 

---

[#taskid X](https://wiris.kanbanize.com/ctrl_board/2/cards/X/details/) (*Waiting for the card to be created*)

2024-05-21 07:15 UTC, jgonzalez-at-wiris approved these changes

2024-05-21 07:20 UTC, usantos-at-wiris requested changes
It seems I can't build Generic, Tiny5 and tiny6 editors. Could you please take a look ?
![image](https://github.com/wiris/html-integrations/assets/164866893/0467315d-ad1a-45ff-a844-f7dcc44554c6)

2024-05-21 07:39 UTC, pau-sala-at-wiris commented
> It seems I can't build Generic, Tiny5 and tiny6 editors. Could you please take a look ? 

I've been able to build and start tiny5, tiny6 and generic with no problems in this branch.

2024-05-21 11:11 UTC, usantos-at-wiris approved these changes

2024-05-27 08:16 UTC, carla-at-wiris approved these changes

2024-05-31 10:06 UTC, merged