fix: change the latex and mathml detection
wiris/html-integrations pull request #995
Opened 2024-07-23 14:44 UTC by usantos-at-wiris

## Description

_What does this PR fix or add?_

## Steps to reproduce

_If this PR solves a bug, include a short summary of the bug and the steps to reproduce it._

---

Closes #X (_Associated GitHub issue, if any_)

[#taskid X](https://wiris.kanbanize.com/ctrl_board/2/cards/X/details/) (_Associated Kanbanize card, if any_)

2024-07-29 13:11 UTC, jgonzalez-at-wiris requested changes

2024-07-29 13:11 UTC, jgonzalez-at-wiris commented on packages/viewer/src/properties.ts
> +    return this.config.blacklist || defaultValues.blacklist;
```suggestion
    return this.config.blacklist ?? defaultValues.blacklist;
```

Sugerencia de tu querido sonarlint!!!!

2024-07-29 13:11 UTC, jgonzalez-at-wiris commented on packages/viewer/src/properties.ts
> +    this.render();
Pregunta por si sabes responder: ¿por qué tras cada función `set` se hace una llamada a `render()`?

2024-07-29 13:11 UTC, jgonzalez-at-wiris commented on packages/viewer/src/latex.ts
> +  const latexNodes = findLatexTextNodes(properties, root);
Es buena práctica pasar a las funciones los argumentos exactos que necesita para funcionar. En este caso, en lugar de pasarle los properties al completo, lo suyo sería pasarle únicamente el campo `blacklist`, que es lo que necesita realmente. De esta forma al leer la llamada de la función se entiende mejor el qué hace por dentro, pasarle las properties al completo es un poco "oscuro".

2024-07-29 13:11 UTC, jgonzalez-at-wiris commented on packages/viewer/src/latex.ts
> +    if (Array.from(blackListedNodes).includes(ancestor as Element)) {
¿Crees que [esto](https://developer.mozilla.org/en-US/docs/Web/API/Node/contains) puede ayudar a simplificar este código?  Lo he sacado de [aquí](https://stackoverflow.com/a/18234150).

2024-07-29 13:25 UTC, usantos-at-wiris commented on packages/viewer/src/latex.ts
> +  const latexNodes = findLatexTextNodes(properties, root);
¡Totalmente cierto! Me parecía que por uniformidad y escalabilidad sería mejor las propiedades. Pero esto se puede cambiar siempre

2024-07-29 13:26 UTC, usantos-at-wiris commented on packages/viewer/src/properties.ts
> +    this.render();
No tengo ni idea AJAJAJ

2024-07-29 14:36 UTC, jgonzalez-at-wiris commented on packages/viewer/src/properties.ts
> +    this.render();
Voy a preguntar por otros lados a ver si me saben responder jeje

2024-07-31 11:37 UTC, jgonzalez-at-wiris submitted a review, later dismissed

2024-08-16 10:41 UTC, jgonzalez-at-wiris approved these changes

2025-01-07 11:31 UTC, xjiang-at-wiris submitted a review, later dismissed

2025-01-07 12:46 UTC, ncornaglia-at-wiris approved these changes

2025-01-07 13:11 UTC, jgonzalez-at-wiris approved these changes

2025-01-07 13:29 UTC, xjiang-at-wiris approved these changes

2025-01-10 09:04 UTC, carla-at-wiris approved these changes

2025-01-21 09:37 UTC, merged